### ISSUE TITLE
Skeleton for CH32V307

### ISSUE THREAD

**Issue by Marcuss2** [ch32-rs/ch32x0-hal#2]
Hey, you mention that you want to turn this repo into a skeleton for the CH32V series as well. Mind if I take a look at it?

**Comment by andelf** [comment]
Feel free to start your work and open PR at https://github.com/ch32-rs/ch32-hal.
You can copy almost all the code base. (The major difference I noticed is that CH32X035's GPIO has 24 lines, while others have 16 lines)
I'll join the dev when I finish OPA peripheral of ch32x0-hal.
